movie_index:
    path:     /
    defaults: { _controller: MovieMovieBundle:Page:index }

movie_about:
    path: /about
    defaults: { _controller: MovieMovieBundle:Page:about }
    requirements:
        _method: GET

movie_new:
    path: /new
    defaults: { _controller: MovieMovieBundle:Page:new }
    requirements:
        _method: GET, POST
