movie_index:
    path:     /
    defaults: { _controller: MovieMovieBundle:Page:index }

movie_show:
    path: /show/{id}
    defaults: { _controller: MovieMovieBundle:Page:show, id: id }
    requirements:
        id: '\d+'

movie_review:
    path: /review/{id}
    defaults: { _controller: MovieMovieBundle:Page:review, id: id }
    requirements:
        id: '\d+'

movie_delete:
    path: /delete/{id}
    defaults: { _controller: MovieMovieBundle:Page:delete, id: id }

movie_edit:
    path: /edit/{id}
    defaults: { _controller: MovieMovieBundle:Page:editMovie, id: id }

movie_review_edit:
    path: /edit/review/{id}
    defaults: { _controller: MovieMovieBundle:Page:editReview, id: id }

movie_about:
    path: /about
    defaults: { _controller: MovieMovieBundle:Page:about }
    requirements:

movie_login:
    path: /login
    defaults: { _controller: MovieMovieBundle:Page:login }
    requirements:

movie_register:
    path: /register
    defaults: { _controller: MovieMovieBundle:Page:register }
    requirements:

movie_new:
    path: /movie/new
    defaults: { _controller: MovieMovieBundle:Page:new }
    requirements:

movie_user:
    path: /user-page/{id}
    defaults: { _controller: MovieMovieBundle:Page:userPage }
    requirements:


