movie_index:
    path:     /
    defaults: { _controller: MovieMovieBundle:Page:index }

movie_show:
    path: /show/{id}
    defaults: { _controller: MovieMovieBundle:Page:show, id: id }
    requirements:
        _method: GET, POST
#        id: '\d+'

movie_show:
    path: /delete/{id}
    defaults: { _controller: MovieMovieBundle:Page:delete, id: id }

movie_about:
    path: /about
    defaults: { _controller: MovieMovieBundle:Page:about }
    requirements:
        _method: GET

movie_login:
    path: /login
    defaults: { _controller: MovieMovieBundle:Page:login }
    requirements:
        _method: GET

movie_register:
    path: /register
    defaults: { _controller: MovieMovieBundle:Page:register }
    requirements:
        _method: GET

movie_new:
    path: /new
    defaults: { _controller: MovieMovieBundle:Page:new }
    requirements:
        _method: GET, POST

movie_newreview:
    path: /movie/new
    defaults: { _controller: MovieMovieBundle:Page:newReview }
    requirements:
        _method: GET, POST

movie_user:
    path: /user-page/{id}
    defaults: { _controller: MovieMovieBundle:Page:userPage }
    requirements:
        _method: GET, POST


