fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

movie_movie:
    resource: "@MovieMovieBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

